/**
 * The client hydration-entry helper (contract R15 — replay hydration).
 *
 * The client no longer receives per-island data: `hydrateDocument(Doc)` (runtime) **replays the
 * document** — re-executes `render(Doc)` with `island()` in capture mode, recovering each island's
 * live component (closure intact), live props, and recomputed slot — then hydrates each captured
 * island over its `[data-hydration-id]` marker. So the generated entry is just wiring:
 *
 * 1. import the compiled `.nota` module's default export (`Doc`);
 * 2. import + `setAdapter` the framework adapter;
 * 3. when a setup module is configured, import it for side effects (client-side
 *    `registerComponents` / `lstset`) and **bake the config baseline** — the replay runs `reset()`
 *    client-side, which restores the `lstset` baseline, so without `bakeConfigBaseline()` the
 *    recomputed slot bytes could diverge from the server's (this mirrors the CLI's SSR entry);
 * 4. `hydrateDocument(Doc)`.
 *
 * This supersedes the manifest-driven boot entry (embedded manifest literal + namespace import +
 * `islandRegistry`/`bootIslandsWithSlots`): no registry, no JSON props, no `innerHTML` slot-scrape.
 * The manifest is now debug metadata only — callers still gate on it (`hasIslands`) so island-free
 * docs keep the zero-JS property, and the CLI still inlines it as a JSON metadata view.
 *
 * The generated string is **source for a bundler** — the CLI esbuild-bundles it (entry + compiled
 * module + adapter + runtime) into one inlinable `<script>`; the playground feeds the same shape to
 * native-ESM + import maps. This helper itself stays bundler-agnostic: a pure `opts → string` code
 * generator.
 */

/** Options for {@link generateClientEntry}. */
export interface ClientEntryOptions {
  /**
   * The module specifier of the **compiled `.nota` module** — its default export is `Doc`, which the
   * entry replays and hydrates. E.g. a relative path to the emitted module on disk
   * (`"./doc.compiled.js"`), or a virtual id the bundler resolves. Required: replay hydration is
   * meaningless without the document to replay.
   */
  moduleId: string;
  /**
   * The framework **adapter** module specifier (default `"@nota-lang/react"`). Its *default export*
   * is the `Adapter`; the entry `setAdapter`s it before `hydrateDocument` (so islands hydrate
   * through the chosen framework). One adapter per build.
   */
  adapterModule?: string;
  /**
   * The `@nota-lang/runtime` specifier (default `"@nota-lang/runtime"`). Overridable for tests /
   * non-standard layouts; `setAdapter` + `hydrateDocument` are imported from here.
   */
  runtimeModule?: string;
  /**
   * Optional **site setup module** specifier, imported for side effects *before* the replay
   * (contract R14b/d): its `registerComponents({…})` / `lstset({…})` calls re-run on the client.
   * When set, the entry also imports `bakeConfigBaseline` from `@nota-lang/prelude` and calls it
   * before `hydrateDocument` — the replay's `reset()` restores the baked baseline, keeping the
   * recomputed slot bytes byte-identical to the server's (mirror of the CLI's `--setup` SSR entry).
   */
  setupModule?: string;
}

/**
 * Generate the client **hydration-entry module** (as a JS source string) for a compiled `.nota`
 * document.
 *
 * The emitted module is wiring only (see the module docs): runtime imports, the adapter (default
 * export), the optional setup import + config bake, the compiled module's `Doc`, and
 * `setAdapter(adapter); hydrateDocument(Doc);`. All hydration *logic* — the capture replay, the
 * determinism guard, the per-island hydrate loop — lives in the runtime.
 *
 * Callers gate on the manifest themselves (`hasIslands`) — an island-free document should get **no
 * client entry at all** (the zero-JS property), not an entry that replays for nothing.
 *
 * @param opts {@link ClientEntryOptions} (at least `moduleId`)
 * @returns the hydration-entry module source — feed it to a bundler (esbuild for the CLI)
 */
export function generateClientEntry(opts: ClientEntryOptions): string {
  const adapterModule = opts.adapterModule ?? "@nota-lang/react";
  const runtimeModule = opts.runtimeModule ?? "@nota-lang/runtime";

  // The setup module runs for its side effects before Doc's module code; the config it set is then
  // baked as the client's per-render reset baseline (see ClientEntryOptions.setupModule).
  const setupImports =
    opts.setupModule !== undefined
      ? `import ${JSON.stringify(opts.setupModule)};
import { bakeConfigBaseline } from "@nota-lang/prelude";
`
      : "";
  const setupBake =
    opts.setupModule !== undefined ? "bakeConfigBaseline();\n" : "";

  return `// Generated by @nota-lang/vite generateClientEntry. Do not edit.
import { setAdapter, hydrateDocument } from ${JSON.stringify(runtimeModule)};
import adapter from ${JSON.stringify(adapterModule)};
${setupImports}import Doc from ${JSON.stringify(opts.moduleId)};

setAdapter(adapter);
${setupBake}hydrateDocument(Doc);
`;
}
