/**
 * `@nota-lang/compiler` — the Node shim around the oxc Nota *reader*.
 *
 * The reader lives in the Rust fork (`oxc::nota::compile`); this package is the JS-side glue that
 * makes its output usable from Node. {@link compile} takes a `.nota` source string and returns the
 * emitted JS module (plus, eventually, a sourcemap), with the `@nota-lang/runtime` import the reader
 * deliberately omits **prepended**. The reader does not emit the `@nota-lang/runtime` import — the
 * compiler shim (or integrator) prepends it.
 *
 * The backend is the node-target wasm reader, `@nota-lang/wasm-node` (`wasm-pack build --target
 * nodejs`; the workspace dep on the repo's `oxc/napi/nota_wasm/pkg-node` in development, an npm
 * package outside it), imported like any other dependency. It exposes the same `oxc::nota` entries
 * (`compile` / `compileVirtual` / `highlight`) in-process — no subprocess, no temp files — so
 * installs need no Rust toolchain and no platform-specific binary.
 */

import * as wasm from "@nota-lang/wasm-node";

/**
 * The shape of the node-target wasm reader's entries this shim calls (`@nota-lang/wasm-node`'s
 * generated `.d.ts` types the payloads as `any`; this is the precise view).
 */
interface WasmReader {
  compile(source: string): { code: string };
  compileVirtual(source: string): VirtualJson;
  highlight(source: string): Uint32Array;
  highlightKindNames(): string[];
}

/** The typed view over the wasm module (in-process and sub-ms — it serves both the build path and
 * per-keystroke semantic tokens). */
const reader = wasm as unknown as WasmReader;

/** The runtime import the reader omits — prepended onto every emit. */
export const RUNTIME_IMPORT =
  'import { h, decode, Fragment, inlineComponent, blockComponent } from "@nota-lang/runtime";\n';

/** Options for {@link compile}. */
export interface CompileOptions {
  /**
   * The original path of the source (e.g. a Vite module id). Names the source in diagnostics and
   * any future sourcemap. Does **not** need to exist on disk.
   */
  sourcePath?: string;
}

/**
 * A standard [Source Map v3](https://tc39.es/ecma426/) object. Declared structurally here (rather
 * than pulling a bundler type) so the shim stays backend-agnostic; it is shaped to be assignable to
 * Vite/Rollup's sourcemap-input type (only `mappings` is required) so it flows straight through
 * `@nota-lang/vite`'s `transform` return.
 */
export interface SourceMapV3 {
  mappings: string;
  version?: number;
  file?: string;
  sources?: (string | null)[];
  sourcesContent?: (string | null)[];
  names?: string[];
  sourceRoot?: string;
}

/** The result of {@link compile}: the emitted JS module and (when available) its sourcemap. */
export interface CompileResult {
  /** The emitted JS module, with the {@link RUNTIME_IMPORT} prepended. */
  code: string;
  /** A {@link SourceMapV3}, when the backend produces one (the reader does not yet — see notes). */
  map?: SourceMapV3;
}

/**
 * Compile a `.nota` source string to an emitted JS module.
 *
 * Runs the in-process wasm reader. The {@link RUNTIME_IMPORT} is prepended to the result. A reader
 * diagnostic is surfaced as the thrown `Error`'s message (raw text also on `.diagnostics`).
 *
 * @param source the `.nota` file contents
 * @param opts   optional {@link CompileOptions}
 * @returns the {@link CompileResult} (`{ code, map? }`)
 * @throws if the reader reports a diagnostic — the error message carries the diagnostic text.
 */
export function compile(
  source: string,
  opts: CompileOptions = {}
): CompileResult {
  let emitted: string;
  try {
    emitted = reader.compile(source).code;
  } catch (err) {
    throw toCompileError(err, opts.sourcePath);
  }

  // Prepend the runtime import the reader omits.
  const code = RUNTIME_IMPORT + emitted;

  // The reader does not surface a sourcemap yet; structured CodeMappings + a flat v3 map are a
  // forthcoming reader upgrade. Once present, parse + return them here. The prepended import
  // shifts generated offsets by one leading line, which a real map must account for (trivial to
  // offset). Kept undefined until the backend emits it.
  return { code, map: undefined };
}

// ===================================================================================================
// The virtual (`.tsx`) emit for the language server.
// ===================================================================================================

/**
 * A Volar `@volar/language-core` `CodeMapping`, as emitted by the reader's `compile_virtual`
 * (`oxc/crates/oxc/src/nota.rs`).
 *
 * Parallel arrays — one *segment* per index `k`: source bytes `[sourceOffsets[k],
 * sourceOffsets[k]+lengths[k])` correspond to generated bytes `[generatedOffsets[k],
 * generatedOffsets[k]+(generatedLengths?.[k] ?? lengths[k]))`. The reader produces one byte-exact
 * leaf per segment, so `generatedLengths` is `null` (generated length == source length) in practice,
 * but the field is carried for fidelity. `data` is the capability flag set (Volar `CodeInformation`).
 *
 * Offsets index the **`.nota`** source (`sourceOffsets`) and the reader's **bare** virtual `.tsx`
 * (`generatedOffsets`) — i.e. *without* the runtime+ambient typing preamble, which the reader omits.
 * The language-server `LanguagePlugin` prepends that preamble and shifts every `generatedOffsets` by
 * its length (`sourceOffsets` unchanged).
 */
export interface CodeMapping {
  /** Source byte offsets into the `.nota` (one per segment). */
  sourceOffsets: number[];
  /** Generated byte offsets into the bare virtual `.tsx` (one per segment). */
  generatedOffsets: number[];
  /** Segment lengths in the source (one per segment). */
  lengths: number[];
  /**
   * Segment lengths in the generated output when they differ from {@link lengths}; `null` ⇒ every
   * segment's generated length equals its source length (the common, byte-exact case).
   */
  generatedLengths: number[] | null;
  /** The Volar `CodeInformation` capability flags for this mapping's range(s). */
  data: MappingCapabilities;
}

/**
 * Volar `CodeInformation` capability flags for a mapped range (the `oxc` `MappingCapabilities`).
 * Each boolean gates a class of IDE feature when the TS service result maps
 * back to the `.nota`: `completion` (autocomplete), `format` (formatting/edits), `navigation`
 * (go-to-def / find-refs / rename), `semantic` (semantic tokens + **hover**), `structure` (outline /
 * folding), `verification` (**diagnostics**, incl. `@Unknown{}` → "Cannot find name").
 */
export interface MappingCapabilities {
  completion: boolean;
  format: boolean;
  navigation: boolean;
  semantic: boolean;
  structure: boolean;
  verification: boolean;
}

/**
 * One recovered Nota diagnostic from the reader's EOF error-recovery on the virtual path: a
 * `message` and the byte span (`start`/`len`) into the **`.nota`** source it points at. The
 * language server maps these to LSP diagnostics. A label-less diagnostic reports
 * `start: 0, len: 0`.
 */
export interface NotaError {
  /** The human-readable diagnostic message. */
  message: string;
  /** Byte offset into the `.nota` source where the diagnostic begins. */
  start: number;
  /** Length in bytes of the diagnostic's span (`0` for a point diagnostic, e.g. at EOF). */
  len: number;
}

/**
 * The result of {@link compileVirtual}: the **bare** virtual `.tsx` (TS types preserved; runtime
 * import + ambient prelude *not* prepended — the language-server adds those), its
 * {@link CodeMapping}s, and any recovered {@link NotaError}s (empty for a well-formed file).
 *
 * The virtual path uses EOF error-recovery, so `compileVirtual` **does not throw** on unterminated
 * markup: it returns a best-effort `code` + `mappings` and reports the syntax/lowering problems in
 * `errors` for the language server to surface as diagnostics.
 */
export interface VirtualCompileResult {
  /** The emitted virtual `.tsx` module (type-preserving, no runtime/ambient preamble). */
  code: string;
  /** The {@link CodeMapping}s mapping `.tsx` offsets back to `.nota` offsets. */
  mappings: CodeMapping[];
  /** Recovered Nota parse/lowering diagnostics (byte-spanned into the `.nota`); empty if clean. */
  errors: NotaError[];
}

/**
 * The raw virtual-emit shape the wasm entry returns (a Rust `None` for `generatedLengths` arrives
 * as `undefined` — {@link validateVirtual} normalizes it to `null`).
 */
interface VirtualJson {
  code: string;
  mappings: CodeMapping[];
  errors?: NotaError[];
}

/**
 * Compile a `.nota` source to the **type-preserving virtual `.tsx`** emit + Volar CodeMappings.
 * The language server (`@nota-lang/language-server`) consumes this.
 *
 * Runs the in-process wasm reader's `compileVirtual`. Unlike {@link compile}, the runtime import is
 * **not** prepended here — the language-server `LanguagePlugin` prepends a runtime+ambient typing
 * preamble (so `h`/`decode`/`useState`/… type-check) and shifts the mappings by its length; doing
 * it here would double-shift.
 *
 * The reader uses **EOF error-recovery** on this path, so it does **not** fail on unterminated
 * markup: a syntax error yields a best-effort `code` + `mappings` and comes back in
 * {@link VirtualCompileResult.errors} for the language server to surface as LSP diagnostics.
 *
 * @param source the `.nota` file contents
 * @param opts   optional {@link CompileOptions}
 * @returns the {@link VirtualCompileResult} (`{ code, mappings, errors }`)
 * @throws only if the reader itself fails (a desynced wasm build). A *recoverable* Nota syntax
 *   error does not throw.
 */
export function compileVirtual(
  source: string,
  opts: CompileOptions = {}
): VirtualCompileResult {
  // The wasm entry returns the already-structured object (camelCase, `errors` always present).
  // Validate the shape anyway — a desynced wasm build should surface a clear error here, not an
  // `undefined` downstream.
  const raw = reader.compileVirtual(source) as VirtualJson;
  return validateVirtual(raw, opts.sourcePath);
}

/**
 * Validate + normalize a raw virtual-emit object (the wasm entry's return value) into a
 * {@link VirtualCompileResult}, so a desynced wasm build surfaces a clear error rather than a
 * downstream `undefined`. Exported for unit-testing the validation against hand-written shapes.
 *
 * @internal
 */
export function validateVirtual(
  parsed: VirtualJson,
  sourcePath?: string
): VirtualCompileResult {
  if (typeof parsed.code !== "string" || !Array.isArray(parsed.mappings)) {
    const where = sourcePath ? ` (${sourcePath})` : "";
    throw new Error(`nota: virtual emit missing \`code\`/\`mappings\`${where}`);
  }
  // Light per-mapping validation: the parallel arrays must be present and equal-length. Cheap, and
  // it catches a desynced backend before the offset-shift math runs in the language server.
  for (const m of parsed.mappings) {
    if (
      !Array.isArray(m.sourceOffsets) ||
      !Array.isArray(m.generatedOffsets) ||
      !Array.isArray(m.lengths) ||
      m.sourceOffsets.length !== m.generatedOffsets.length ||
      m.sourceOffsets.length !== m.lengths.length
    ) {
      throw new Error(
        "nota: virtual CodeMapping has missing or mismatched-length offset arrays"
      );
    }
  }
  // Normalize `generatedLengths` to `null` (serde-wasm-bindgen serializes a Rust `None` as
  // `undefined`; the declared type is `number[] | null`).
  const mappings = parsed.mappings.map(m => ({
    ...m,
    generatedLengths: m.generatedLengths ?? null
  }));
  // `errors` is optional for forward-compat with a wasm build that predates recovered-error
  // reporting (treated as "no diagnostics");
  // a present array is validated to the `{message, start, len}` shape.
  const errors: NotaError[] = Array.isArray(parsed.errors)
    ? parsed.errors.map(e => ({
        message: String(e.message),
        start: Number(e.start) || 0,
        len: Number(e.len) || 0
      }))
    : [];
  return { code: parsed.code, mappings, errors };
}

// ===================================================================================================
// Reader-driven syntax highlight spans.
// ===================================================================================================

/**
 * One reader-faithful highlight span over the **`.nota`** source: a `[start, end)` byte range and
 * its kind (a stable kebab-case name — `"tag-host"`, `"js-keyword"`, `"emphasis-strong"`, …). This
 * is the reader's `parse_nota_highlights` output the CodeMirror playground already paints; the
 * language server consumes it for reader-driven **semantic tokens**.
 */
export interface HighlightSpan {
  /** `.nota` byte offset of the span's first byte. */
  start: number;
  /** `.nota` byte offset one past the span's last byte. */
  end: number;
  /** The stable kebab-case highlight-kind name (index into {@link highlightKindNames}). */
  kind: string;
}

let cachedKindNames: string[] | null = null;

/**
 * The stable kebab-case highlight-kind names, in discriminant order (index a {@link HighlightSpan}'s
 * `kind` triple value into this). Cached after the first call.
 */
export function highlightKindNames(): string[] {
  if (!cachedKindNames) {
    cachedKindNames = reader.highlightKindNames();
  }
  return cachedKindNames;
}

/**
 * Reader-faithful syntax highlight spans for a whole `.nota` source, decoded from the wasm reader's
 * flat `[start, end, kind]` `Uint32Array` triples into named {@link HighlightSpan}s. Spans are
 * source-native (no preamble shift) and already sorted start-ascending / end-descending (outer
 * spans before the spans they contain — paint in list order).
 *
 * @param source the `.nota` file contents
 * @returns the highlight spans
 * @throws if the source fails to parse (the reader's `highlight` throws) — callers that want editor
 *   resilience (the semantic-tokens plugin) should catch and serve their last-good spans.
 */
export function highlightSpans(source: string): HighlightSpan[] {
  const names = highlightKindNames();
  const flat = reader.highlight(source);
  const spans: HighlightSpan[] = [];
  for (let i = 0; i + 2 < flat.length; i += 3) {
    const kindIndex = flat[i + 2];
    spans.push({
      start: flat[i],
      end: flat[i + 1],
      kind: names[kindIndex] ?? String(kindIndex)
    });
  }
  return spans;
}

/**
 * Normalize a thrown wasm-reader error (a `JsError` whose message is the newline-joined
 * diagnostics) into a `nota: failed to compile` message naming the source, with the raw diagnostic
 * text on `.diagnostics` for programmatic consumers (e.g. a Vite error overlay).
 */
function toCompileError(err: unknown, sourcePath?: string): Error {
  const diagnostics =
    err instanceof Error ? err.message : String(err ?? "nota: compile failed");
  const where = sourcePath ? ` (${sourcePath})` : "";
  const error = new Error(`nota: failed to compile${where}\n${diagnostics}`);
  (error as Error & { diagnostics?: string }).diagnostics = diagnostics;
  return error;
}
