/**
 * The Nota Volar **`LanguagePlugin`** — the core of the language server.
 *
 * It turns a `.nota` source into a {@link VirtualCode}: the typing preamble + the reader's virtual
 * `.tsx` as the snapshot, plus the reader's `CodeMapping`s with every `generatedOffsets` shifted by
 * the preamble length (the preamble-shift rule). Volar then drives the standard TS
 * language service over the virtual `.tsx` (via `@volar/typescript`, keyed by the `typescript`
 * field's `getServiceScript`), and maps results — diagnostics, hover, completion,
 * rename — back to `.nota` ranges through these mappings.
 */

import {
  compileVirtual,
  type NotaError,
  type CodeMapping as ReaderCodeMapping
} from "@nota-lang/compiler";
import type {
  LanguagePlugin,
  VirtualCode,
  CodeMapping as VolarCodeMapping
} from "@volar/language-core";
import type { TypeScriptServiceScript } from "@volar/typescript";
import ts from "typescript";
import type { URI } from "vscode-uri";
import { PREAMBLE, PREAMBLE_LENGTH } from "./preamble.js";

/** The `languageId` Volar tags `.nota` source scripts with. */
export const NOTA_LANGUAGE_ID = "nota";

/**
 * The `languageId` the virtual code is emitted as — `typescriptreact`: the reader's virtual emit
 * is type-preserving **Solid JSX**, matching the `.tsx` extension `@volar/typescript` is told to
 * treat the script as.
 */
export const VIRTUAL_LANGUAGE_ID = "typescriptreact";

/**
 * Shift a reader `CodeMapping`'s `generatedOffsets` by {@link PREAMBLE_LENGTH} and adapt it to the
 * Volar `Mapping` shape (the preamble-shift rule). **This is the core fidelity operation** —
 * tested directly in `tests/mapping.test.ts`.
 *
 * - `generatedOffsets[k] → generatedOffsets[k] + shift` (the prepended preamble pushes the bare
 *   `.tsx` forward by `shift` bytes).
 * - `sourceOffsets` — **unchanged** (the `.nota` source is untouched; the reader omitted the import).
 * - `lengths` — unchanged (segment lengths are invariant under a pure prepend).
 * - `generatedLengths` — `null` (the byte-exact common case) becomes `undefined` (Volar's optional);
 *   a present array is carried through verbatim (lengths are position-independent).
 * - `data` — the reader's `MappingCapabilities` (all-boolean) is structurally a Volar
 *   `CodeInformation` (each field `boolean | {…}`), passed through as the capability gate.
 *
 * Pure: returns fresh arrays, never mutates the input (the reader's result may be reused).
 *
 * @param mappings the reader's mappings over the *bare* `.tsx`
 * @param shift    bytes to add to every generated offset (the preamble length)
 */
export function shiftMappings(
  mappings: readonly ReaderCodeMapping[],
  shift: number
): VolarCodeMapping[] {
  return mappings.map(m => ({
    sourceOffsets: m.sourceOffsets.slice(),
    generatedOffsets: m.generatedOffsets.map(o => o + shift),
    lengths: m.lengths.slice(),
    // Volar uses `generatedLengths?: number[]` (optional); the reader uses `number[] | null`.
    ...(m.generatedLengths != null
      ? { generatedLengths: m.generatedLengths.slice() }
      : {}),
    // `MappingCapabilities` (all booleans) is assignable to Volar's `CodeInformation`.
    data: m.data
  }));
}

/**
 * The bytes a mapping segment may be **extended across** for completion positions. The reader's
 * segments are byte-exact *leaf tokens* (identifiers/literals); the position right after a trailing
 * `.` — exactly where the user expects member completion on `x.|` — falls in the unmapped
 * inter-token gap, so Volar cannot translate it and completion comes back empty. The reader's
 * `CodeMapping` contract explicitly allows downstream coalescing; we extend a segment while the
 * next source and generated bytes are identical AND in this set. Restricted to the member-access
 * bytes (`.`, `?` for `?.`) on purpose: extending across arbitrary coincidentally-equal bytes
 * (e.g. the `)` closing both `@(x)` and the generated call) would map *markup* positions into the
 * virtual `.tsx` and produce completion noise where Nota, not TS, owns the surface.
 */
const EXTEND_BYTES = new Set([".".codePointAt(0), "?".codePointAt(0)]);

/**
 * Extend the reader's byte-exact segments across trailing member-access bytes (see
 * {@link EXTEND_BYTES}), so `x.|` / `x?.|` positions map into the virtual `.tsx` and TS serves
 * member completions. Byte-identity keeps the linear-offset premise of the reader's leaves; the
 * extension caps at the next segment of the same mapping (segments stay disjoint). Zero-width
 * anchors (`generatedLengths` present) pass through untouched. Pure; offsets are in the same
 * space the reader emits (UTF-8 bytes — compared byte-wise).
 */
export function extendMappings(
  source: string,
  bare: string,
  mappings: readonly ReaderCodeMapping[]
): ReaderCodeMapping[] {
  const src = new TextEncoder().encode(source);
  const gen = new TextEncoder().encode(bare);
  return mappings.map(m => {
    if (m.generatedLengths != null) {
      return m;
    }
    const lengths = m.lengths.slice();
    for (let i = 0; i < m.sourceOffsets.length; i++) {
      const cap =
        i + 1 < m.sourceOffsets.length ? m.sourceOffsets[i + 1] : src.length;
      let s = m.sourceOffsets[i] + lengths[i];
      let g = m.generatedOffsets[i] + lengths[i];
      while (
        s < cap &&
        g < gen.length &&
        src[s] === gen[g] &&
        EXTEND_BYTES.has(src[s])
      ) {
        lengths[i]++;
        s++;
        g++;
      }
    }
    return { ...m, lengths };
  });
}

/**
 * Build the virtual `.tsx` source + shifted mappings for a `.nota` source string. Split out from the
 * `LanguagePlugin` so it is unit-testable without any Volar/TS plumbing (the mapping-fidelity
 * test calls this directly).
 *
 * The virtual path uses EOF error-recovery, so an unterminated `.nota` still yields a (best-effort)
 * virtual + mappings; the recovered syntax diagnostics come back in `errors` (byte-spanned into the
 * `.nota`) for the diagnostics service plugin (`./diagnostics.ts`) to surface.
 *
 * @param source the `.nota` file contents
 * @returns `{ code }` = {@link PREAMBLE} + bare virtual `.tsx`; `{ mappings }` = shifted to index it;
 *   `{ errors }` = recovered Nota diagnostics (empty for a well-formed file).
 */
export function buildVirtual(source: string): {
  code: string;
  mappings: VolarCodeMapping[];
  errors: NotaError[];
} {
  const { code: bare, mappings, errors } = compileVirtual(source);
  return {
    code: PREAMBLE + bare,
    mappings: shiftMappings(
      extendMappings(source, bare, mappings),
      PREAMBLE_LENGTH
    ),
    errors
  };
}

/**
 * The Nota `VirtualCode` for one `.nota` file: a single root whose snapshot is the preamble +
 * virtual `.tsx`, mapped back to the `.nota` via the shifted mappings. There are no nested
 * `embeddedCodes` — the whole virtual file is one TS document (the markup lowered to `h(...)` calls
 * inline), so Volar/TS treat it as a single `.tsx` script.
 */
export interface NotaVirtualCode extends VirtualCode {
  id: "root";
  languageId: typeof VIRTUAL_LANGUAGE_ID;
}

/**
 * Create the {@link NotaVirtualCode} for a snapshot. The reader now **recovers** from a Nota syntax
 * error (EOF error-recovery), so a mid-edit `.nota` still produces a best-effort virtual `.tsx` +
 * mappings — TS features (hover/completion/diagnostics) keep working over the parsed prefix instead
 * of blanking out. The Nota syntax diagnostics themselves flow through a separate channel
 * (`./diagnostics.ts`). The `try/catch` now only guards a true *backend* failure (a desynced
 * `@nota-lang/compiler` wasm build), for which we degrade to an empty TS module so the server
 * stays alive.
 */
function createNotaVirtualCode(snapshot: ts.IScriptSnapshot): NotaVirtualCode {
  const source = snapshot.getText(0, snapshot.getLength());
  let code: string;
  let mappings: VolarCodeMapping[];
  try {
    ({ code, mappings } = buildVirtual(source));
  } catch {
    // The reader binary itself failed to run (not a syntax error — recovery handles those).
    // Degrade gracefully: an empty TS module so the server stays alive.
    code = PREAMBLE;
    mappings = [];
  }
  return {
    id: "root",
    languageId: VIRTUAL_LANGUAGE_ID,
    snapshot: ts.ScriptSnapshot.fromString(code),
    mappings
  };
}

/**
 * The `getServiceScript` hook (the `@volar/typescript` `LanguagePlugin.typescript` extension):
 * declares that the root virtual code **is** the TS-checkable script, as a `.tsx`. This is what
 * routes the TS language service onto our virtual `.tsx` (and thus diagnostics/hover/etc. back
 * through the mappings).
 */
function getServiceScript(
  root: VirtualCode
): TypeScriptServiceScript | undefined {
  if (root.id !== "root") {
    return undefined;
  }
  return {
    code: root,
    extension: ".tsx",
    scriptKind: ts.ScriptKind.TSX
  };
}

/**
 * The Nota `LanguagePlugin<URI>` (generic param `URI` — Volar's node server keys scripts by `URI`).
 *
 * - `getLanguageId(uri)` → `"nota"` for `*.nota` (so unopened `.nota` files are still recognized),
 *   `undefined` otherwise (defer to other plugins / TS itself).
 * - `createVirtualCode(uri, languageId, snapshot)` → the {@link NotaVirtualCode} when `languageId`
 *   is `"nota"`.
 * - `typescript.extraFileExtensions` registers `.nota` with the TS project (deferred script kind, not
 *   a TS extension itself — its *virtual* `.tsx` is what TS sees); `getServiceScript` points TS at
 *   that virtual `.tsx`.
 */
export const notaLanguagePlugin: LanguagePlugin<URI, NotaVirtualCode> = {
  getLanguageId(uri) {
    if (uri.path.endsWith(".nota")) {
      return NOTA_LANGUAGE_ID;
    }
    return undefined;
  },

  createVirtualCode(_uri, languageId, snapshot) {
    if (languageId !== NOTA_LANGUAGE_ID) {
      return undefined;
    }
    return createNotaVirtualCode(snapshot);
  },

  updateVirtualCode(_uri, _virtualCode, newSnapshot) {
    // No incremental update — recompile from the new snapshot (the reader is fast).
    return createNotaVirtualCode(newSnapshot);
  },

  typescript: {
    extraFileExtensions: [
      {
        extension: "nota",
        isMixedContent: true,
        // `.nota` carries no TS by itself; its virtual `.tsx` is the deferred TS script.
        scriptKind: ts.ScriptKind.Deferred
      }
    ],
    getServiceScript
  }
};
