/**
 * **Mapping fidelity** — the *core* test. Wrong mappings break every downstream feature, so this is
 * tested first and hardest.
 *
 * Two halves:
 *  1. **The preamble-shift math, explicitly** (`shiftMappings`): a synthetic reader mapping over a
 *     bare `.tsx`, shifted by a known constant — assert `generatedOffsets += shift`, `sourceOffsets`
 *     unchanged, `lengths` unchanged, `null` `generatedLengths` → absent (Volar's optional). This
 *     pins the preamble-shift rule independent of the reader's exact output.
 *  2. **The live round-trip** (`buildVirtual` over a real `.nota` with embedded JS): a source offset
 *     inside an embedded-JS span maps to the **shifted** generated offset, and the generated slice
 *     equals the source token (`src.slice(so, so+len) === code.slice(go, go+len)`). This is the
 *     property that makes the whole mapping correct.
 */

import type { CodeMapping as ReaderCodeMapping } from "@nota-lang/compiler";
import { describe, expect, test } from "vitest";
import { extendMappings } from "../src/language-plugin";
import {
  buildVirtual,
  PREAMBLE,
  PREAMBLE_LENGTH,
  shiftMappings
} from "../src/lib";

describe("extendMappings (member-access segment extension)", () => {
  const caps = {
    completion: true,
    format: true,
    navigation: true,
    semantic: true,
    structure: true,
    verification: true
  };
  const seg = (so: number[], go: number[], len: number[]) => ({
    sourceOffsets: so,
    generatedOffsets: go,
    lengths: len,
    generatedLengths: null,
    data: caps
  });

  test("extends across a byte-identical trailing dot", () => {
    const [m] = extendMappings("x.", "x.;", [seg([0], [0], [1])]);
    expect(m.lengths).toEqual([2]);
  });
  test("extends across `?.` and caps at the next segment", () => {
    // `x?.y` — leaf `x` widens over `?.` but stops where leaf `y` begins.
    const [m] = extendMappings("x?.y", "x?.y", [seg([0, 3], [0, 3], [1, 1])]);
    expect(m.lengths).toEqual([3, 1]);
  });
  test("does not extend over non-member bytes, even when identical", () => {
    const [m] = extendMappings("x)", "x)", [seg([0], [0], [1])]);
    expect(m.lengths).toEqual([1]);
  });
  test("does not extend when the generated byte differs", () => {
    const [m] = extendMappings("x.", "x;", [seg([0], [0], [1])]);
    expect(m.lengths).toEqual([1]);
  });
  test("leaves zero-width anchors (generatedLengths present) untouched", () => {
    const anchor = {
      sourceOffsets: [3],
      generatedOffsets: [10],
      lengths: [0],
      generatedLengths: [0],
      data: caps
    };
    const [m] = extendMappings("@a[.", "h(...).", [anchor]);
    expect(m).toBe(anchor);
  });
});

const FULL_CAPS = {
  completion: true,
  format: true,
  navigation: true,
  semantic: true,
  structure: true,
  verification: true
} as const;

describe("preamble", () => {
  test("PREAMBLE is whole lines (every line ends in \\n) so the shift is a clean constant", () => {
    expect(PREAMBLE.endsWith("\n")).toBe(true);
    expect(PREAMBLE_LENGTH).toBe(PREAMBLE.length);
    // The structural Solid JSX surface the reader references as free identifiers (`NotaDoc`,
    // `For`, …) is declared module-locally (resolution-independent: no import, so they resolve
    // with no node_modules).
    expect(PREAMBLE).toContain("declare const NotaDoc");
    expect(PREAMBLE).toContain("declare const For");
    // The ambient prelude free identifiers are declared.
    expect(PREAMBLE).toContain("declare const createSignal:");
  });
});

describe("shiftMappings (the preamble-shift rule)", () => {
  test("shifts generatedOffsets by the constant, leaves sourceOffsets/lengths untouched", () => {
    const shift = 238;
    const bare: ReaderCodeMapping = {
      sourceOffsets: [8, 33],
      generatedOffsets: [39, 96],
      lengths: [1, 4],
      generatedLengths: null,
      data: { ...FULL_CAPS }
    };

    const [m] = shiftMappings([bare], shift);

    // sourceOffsets unchanged — the .nota source is untouched (the reader omitted the import).
    expect(m.sourceOffsets).toEqual([8, 33]);
    // generatedOffsets each pushed forward by `shift`.
    expect(m.generatedOffsets).toEqual([39 + shift, 96 + shift]);
    // lengths are position-invariant under a pure prepend.
    expect(m.lengths).toEqual([1, 4]);
    // null generatedLengths (byte-exact common case) → omitted (Volar's optional field).
    expect(m.generatedLengths).toBeUndefined();
    // capabilities carried through verbatim as the Volar CodeInformation.
    expect(m.data).toEqual(FULL_CAPS);
  });

  test("is pure — does not mutate the input mapping's arrays", () => {
    const bare: ReaderCodeMapping = {
      sourceOffsets: [0],
      generatedOffsets: [10],
      lengths: [3],
      generatedLengths: null,
      data: { ...FULL_CAPS }
    };
    const before = JSON.parse(JSON.stringify(bare));
    shiftMappings([bare], 100);
    expect(bare).toEqual(before);
  });

  test("carries a present generatedLengths array through verbatim (length is position-independent)", () => {
    const bare: ReaderCodeMapping = {
      sourceOffsets: [5],
      generatedOffsets: [20],
      lengths: [4],
      generatedLengths: [6],
      data: { ...FULL_CAPS }
    };
    const [m] = shiftMappings([bare], 50);
    expect(m.generatedOffsets).toEqual([70]);
    expect(m.generatedLengths).toEqual([6]);
  });
});

describe("buildVirtual (live round-trip over embedded JS)", () => {
  // The fixture: an embedded-JS `%` statement (with a TS type annotation) + a `@(user)`
  // interpolation. Both `count`/`n` (the `%` body) and `user` are embedded-JS spans the reader maps.
  const SOURCE = "% const n: number = count()\n@p{@(user)}\n";

  test("prepends the preamble and shifts every generated offset past it", () => {
    const { code, mappings } = buildVirtual(SOURCE);

    // The virtual .tsx begins with the preamble verbatim.
    expect(code.startsWith(PREAMBLE)).toBe(true);
    // Every generated offset lands inside the post-preamble region (never points into the preamble).
    for (const m of mappings) {
      for (const go of m.generatedOffsets) {
        expect(go).toBeGreaterThanOrEqual(PREAMBLE_LENGTH);
      }
    }
  });

  test("ROUND-TRIP: every mapped segment's generated slice equals its source token", () => {
    const { code, mappings } = buildVirtual(SOURCE);
    let segments = 0;
    for (const m of mappings) {
      for (let k = 0; k < m.sourceOffsets.length; k++) {
        const so = m.sourceOffsets[k];
        const go = m.generatedOffsets[k];
        const len = m.lengths[k];
        const genLen = m.generatedLengths?.[k] ?? len;
        const srcTok = SOURCE.slice(so, so + len);
        const genTok = code.slice(go, go + genLen);
        // The reader produces byte-exact leaves: generated slice === source slice.
        expect(genTok).toBe(srcTok);
        segments++;
      }
    }
    // Sanity: the fixture actually produced mapped segments (so the round-trip wasn't vacuous).
    expect(segments).toBeGreaterThan(0);
  });

  test("the `user` interpolation maps to the shifted generated offset (explicit shift math)", () => {
    const { code, mappings } = buildVirtual(SOURCE);

    // Locate `user` in the source: `@(user)` → the `user` token.
    const srcUser = SOURCE.indexOf("user");
    expect(srcUser).toBeGreaterThan(0);

    // Find the segment whose sourceOffset is exactly `srcUser`.
    let found: { go: number; len: number } | undefined;
    for (const m of mappings) {
      for (let k = 0; k < m.sourceOffsets.length; k++) {
        if (m.sourceOffsets[k] === srcUser) {
          found = { go: m.generatedOffsets[k], len: m.lengths[k] };
        }
      }
    }
    expect(found, "a mapping for `user` must exist").toBeDefined();

    // Its generated offset is the *bare* offset + PREAMBLE_LENGTH, and the slice is "user".
    const { go, len } = found!;
    expect(code.slice(go, go + len)).toBe("user");
    // And the bare offset (go - PREAMBLE_LENGTH) is a valid index into a hypothetical bare emit:
    // i.e. removing the preamble would land `user` at a non-negative offset.
    expect(go - PREAMBLE_LENGTH).toBeGreaterThanOrEqual(0);
  });
});

describe("buildVirtual — non-ASCII fixtures (UTF-8 byte offset → UTF-16 offset at the mapping boundary)", () => {
  // The reader's CodeMapping offsets are UTF-8 BYTE offsets on both sides (compiler lib.ts); Volar's
  // `Mapping` (what `buildVirtual` must return) indexes a JS string, i.e. UTF-16 code units. "café —
  // " ahead of the interpolation is a multibyte prefix where the two spaces diverge: 'é' is 2 UTF-8
  // bytes / 1 UTF-16 unit, '—' is 3 UTF-8 bytes / 1 UTF-16 unit — 10 bytes vs. 7 UTF-16 units, a
  // 3-unit divergence by the time `user` starts. If the mapping boundary ever regresses to passing
  // the reader's byte offsets straight through as though they were already UTF-16 (the historical
  // bug this pins), every assertion below fails.
  const SOURCE = "% const n: number = count()\n@p{café — @(user)}\n";

  test("ROUND-TRIP still holds: every mapped segment's generated slice equals its source token", () => {
    const { code, mappings } = buildVirtual(SOURCE);
    let segments = 0;
    for (const m of mappings) {
      for (let k = 0; k < m.sourceOffsets.length; k++) {
        const so = m.sourceOffsets[k];
        const go = m.generatedOffsets[k];
        const len = m.lengths[k];
        const genLen = m.generatedLengths?.[k] ?? len;
        expect(code.slice(go, go + genLen)).toBe(SOURCE.slice(so, so + len));
        segments++;
      }
    }
    expect(segments).toBeGreaterThan(0);
  });

  test('the `user` interpolation — AFTER a multibyte prefix — still maps to exactly "user"', () => {
    const { code, mappings } = buildVirtual(SOURCE);
    // `String.prototype.indexOf` counts UTF-16 code units — exactly what a mapped `sourceOffsets`
    // entry must now equal.
    const srcUser = SOURCE.indexOf("user");
    expect(srcUser).toBeGreaterThan(0);

    let found: { go: number; len: number } | undefined;
    for (const m of mappings) {
      for (let k = 0; k < m.sourceOffsets.length; k++) {
        if (m.sourceOffsets[k] === srcUser) {
          found = { go: m.generatedOffsets[k], len: m.lengths[k] };
        }
      }
    }
    expect(found, "a mapping for `user` must exist").toBeDefined();
    const { go, len } = found!;
    expect(code.slice(go, go + len)).toBe("user");
  });
});
