/** Regenerate the resolution-independent typing preamble. */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildPreamble } from "../src/preamble-gen.ts";

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "preamble.generated.ts"
);

const preamble = buildPreamble();
const preambleByteLength = Buffer.byteLength(preamble, "utf8");
const file = `/**
 * Generated by \`scripts/gen-preamble.ts\`. Do not edit directly.
 */

/** Ambient declarations prepended to every virtual TSX document. */
export const PREAMBLE = ${JSON.stringify(preamble)};

// PREAMBLE_LENGTH is generated as a UTF-8 byte length; keep the preamble ASCII.
if (/[^\\x00-\\x7f]/.test(PREAMBLE)) {
  throw new Error(
    "preamble.generated.ts: PREAMBLE must be pure ASCII — PREAMBLE_LENGTH is baked as a UTF-8 byte length at generation time (see scripts/gen-preamble.ts)"
  );
}

/** UTF-8 byte length used to shift generated mappings past the preamble. */
export const PREAMBLE_LENGTH = ${preambleByteLength};
`;

writeFileSync(OUT, file, "utf8");
// eslint-disable-next-line no-console
console.log(
  `wrote ${OUT} (${preamble.length} UTF-16 units, ${preambleByteLength} UTF-8 bytes)`
);
